connections:
  default:
    host: localhost
    port: 5672
    username: admin
    password: admin
    heartbeat: 10
    timeout: 2

consumers:
  printer:
    exchange: general-sentiment-x
    routing_key: general-sentiment-q
    queue: general-sentiment-q

rpc-services:
  fetcher:
    exchange: fetcher-x
    routing_key: fetcher-k
    queue: fetcher-q
    response_exchange: fetching-result-x
  fetcher-service:
    exchange: fetcher-x
    routing_key: fetcher-k
    queue: fetcher-q
    response_exchange: fetching-result-x