connections:
  default:
    host: localhost
    port: 5672
    username: user
    password: bitnami

consumers:
  email-sender:
    exchange: notification-sender-x
    exchange_type: topic
    routing_key: "email.#"
    queue: email-sender-q
