connections:
  default:
    host: localhost
    port: 5672
    username: admin
    password: admin

services:
  printer:
    log_level: info
    consumer:
      exchange: general-sentiment-x
      routing_key: general-sentiment-q
      queue: general-sentiment-q
    publisher:
      exchange: general-sentiment-x
      routing_key: general-sentiment-q